### PR TITLE
TOPS-867 - BQ editor and jobUser

### PR DESCRIPTION
**Pull request by kthhrv**
- bigquery.dataEditor for gcp-data-engineers on landing and processing
- bigquery.jobUser for gcp-data-engineers on landing and processing

### CODE REVIEW

**Review by Munir93 — APPROVED** [review]
LGTM!

**Comment by kthhrv** [comment]
@Munir93 remind me again why engineers need BQeditor on landing? isn't that only written to by data-apps using the processing SA?

**Comment by kthhrv** [comment]
lets merge this https://github.com/timeoutdigital/google-search-console-etl-pipeline/pull/2 and rebase your PR off it?

**Comment by Munir93** [comment]
> @Munir93 remind me again why engineers need BQeditor on landing? isn't that only written to by data-apps using the processing SA?

Since this is where our raw data lives DEs will sometimes need to run queries and create tmp datasets/tables during development

**Review by flatnine — APPROVED** [review]

**Pull request closed without merging**
